project:
  type: book
  output-dir: docs

book:
  title: "DL-Note"
  author: "ChoCho"
  date: today
  description: |
    Test.
  chapters:
    - index.qmd
    # - slide/2022-12-27.ipynb
    # - Preliminaries.ipynb
    # - summary.qmd
    # - intro.qmd
    # - Test.qmd
    # - Test2.qmd
    # - appendix_py.ipynb
    - references.qmd
    
  
  page-footer:
    left: |
      DL-Note
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.

  cover-image: cover.jpg

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-link: true
    # include-in-header: "plausible.html"
    callout-appearance: simple

  pdf:
  # See https://quarto.org/docs/reference/formats/pdf.html
    include-in-header:
      - preamble.tex
    documentclass: book
    # documentclass: scrreprt
    papersize: a4
    geometry: 
      - top=2.5cm, 
      - bottom=2.5cm, 
      - left=2cm, 
      - right=2cm


